backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Articles"
    folder: "src/pages/articles"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Author", name: "author", widget: "string", default: "aby" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Keywords"
        name: "keywords"
        widget: "list"
      - label: Featured Image
        name: image
        widget: object
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Alt, name: alt, widget: string }
      - label: "Tags"
        name: "tags"
        widget: "list"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - { label: Quote, name: quote, widget: string }
          - label: Author
            name: author
            widget: object
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Avatar, name: avatar, widget: image }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
